POST http://localhost:3001/products/experiencias

Content-Type: application/json
[
{
    "name":"El Paraiso paisa2",
    "provider": "Organización Parkway",
    "origen": "Bogotá",
    "destination": "Risaralda",
    "hotel": "El Viento",
    "room": [
        {
            "type": "niños",
            "price": "$300.000",
            "rangeAgeKids": "2-12"
        },
        {
            "type": "sencilla",
            "price": "$400.000"
        },
        {
            "type": "doble",
            "price": "$500.000"
        },
        {
            "type": "triple",
            "price": "$600.000"
        }
    ],
    "transport": "Avión",
    "activeDate": "n/a",
    "disableDate": "n/a",
    "description": "n/a",
    "activeProduct": true
}

]

//Hospedajes

{
    "name":"Las Palmas",
    "provider": "Organización Parkway",
    "origen": "Bogotá",
    "destination": "Risaralda",
    "room": [
        {
            "type": "niños",
            "highSeason": "$300.000",
            "lowSeason": "$250.000",
            "rangeAgeKids": "2-10"
        },
        {
            "type": "sencilla",
            "highSeason": "4300.000",
            "lowSeason": "$350.000",
        },
        {
            "type": "doble",
            "highSeason": "5300.000",
            "lowSeason": "$450.000",
        }
    ],
    "activeDate": "n/a",
    "disableDate": "n/a",
    "description": "n/a",
    "activeProduct": true
}

//Traslados

{
   "provider": "Organización Parkway",
    "origen": "Bogotá",
    "destination": "Risaralda",
    "price": "$30.000",
    "pax": "1",
    "description": "n/a",
    "activeProduct": true
    
}

//Actividades

{
    "name": "Paseo por Bogotá",
    "provider": "Organización Parkway",
    "destination": "Risaralda",
    "price": "$30.000",
    "pax": "1",
    "description": "n/a",
    "activeProduct": true
}

//Asistencias

{
    "name": "Colsanitas",
    "provider": "Organización Parkway",
    "destination": "Nacional",
    "price": "$30.000",
    "pax": "1",
    "description": "n/a",
    "activeProduct": true
}