POST http://localhost:3001/products/experiencias

Content-Type: application/json
[
{
    "name":"El Paraiso paisa",
    "provider": "Organización Parkway",
    "origin": "Bogota",
    "destination": "Risaralda",
    "accommodation": [
        {
            "hotel":"El Viento",            
            "room": [
                {
                    "type": "niños",
                    "highSeasonPrice": "$300.000",
                    "lowSeasonPrice": "$250.000",
                    "rangeAgeKids": "2-12"
                },
                {
                    "type": "sencilla",
                    "highSeasonPrice": "$300.000",
                    "lowSeasonPrice": "$250.000",
                },
                {
                    "type": "doble",
                    "highSeasonPrice": "$300.000",
                    "lowSeasonPrice": "$250.000",
                },
                {
                    "type": "triple",
                    "highSeasonPrice": "$300.000",
                    "lowSeasonPrice": "$250.000",
                }
            ]
        }
    ],
    "transport": "Avión",
    "activeDate": "n/a",
    "disableDate": "n/a",
    "description": "n/a",
    "activeProduct": true
}

]

//Hospedajes

{
    "name":"Las Palmas",
    "provider": "Organización Parkway",
    "destination": "Bucaramamga",
    "room": [
        {
            "type": "niños",
            "highSeasonPrice": "$300.000",
            "lowSeasonPrice": "$250.000",
            "rangeAgeKids": "2-10"
        },
        {
            "type": "sencilla",
            "highSeasonPrice": "4300.000",
            "lowSeasonPrice": "$350.000",
        },
        {
            "type": "doble",
            "highSeasonPrice": "5300.000",
            "lowSeasonPrice": "$450.000",
        }
    ],
    "highSeasonDate": "n/a",
    "lowSeasonDate": "n/a",
    "description": "n/a",
    "activeProduct": true
}

//Traslados

{
   "provider": "Organización Parkway",
    "origin": "Medellin",
    "destination": "Bucaramanga",
    "price": "$30.000",
    "pax": "1",
    "description": "n/a",
    "activeProduct": true    
}

//Actividades

{
    "name": "Paseo por Bogotá1",
    "provider": "Organización Parkway",
    "destination": "Medellin",
    "price": "$30.000",
    "pax": "1",
    "description": "n/a",
    "activeProduct": true
}

//Asistencias

{
    "name": "Colsanitas",
    "provider": "Organización Parkway",
    "destination": "Nacional",
    "price": "$30.000",
    "description": "n/a",
    "activeProduct": true
}